name: chat_color
description: Finally &csomeone &rwho &lactually &nGETS &r&aME!
version: 1.0.0
repository: https://github.com/ArcaneArts/chat_color
environment:
  sdk: ^3.4.3
dependencies:
  color: ^3.0.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
